package com.app.vpn;

import android.os.Bundle;
import android.util.Log;
import android.view.View;

import com.app.vpn.bean.Server;

import de.blinkt.openvpn.base.VPNActivity;


public class MainActivity extends VPNActivity implements VPNActivity.VPNStatusListener {

    String data = "###############################################################################\n" +
            "# OpenVPN 2.0 Sample Configuration File\n" +
            "# for PacketiX VPN / SoftEther VPN Server\n" +
            "# \n" +
            "# !!! AUTO-GENERATED BY SOFTETHER VPN SERVER MANAGEMENT TOOL !!!\n" +
            "# \n" +
            "# !!! YOU HAVE TO REVIEW IT BEFORE USE AND MODIFY IT AS NECESSARY !!!\n" +
            "# \n" +
            "# This configuration file is auto-generated. You might use this config file\n" +
            "# in order to connect to the PacketiX VPN / SoftEther VPN Server.\n" +
            "# However, before you try it, you should review the descriptions of the file\n" +
            "# to determine the necessity to modify to suitable for your real environment.\n" +
            "# If necessary, you have to modify a little adequately on the file.\n" +
            "# For example, the IP address or the hostname as a destination VPN Server\n" +
            "# should be confirmed.\n" +
            "# \n" +
            "# Note that to use OpenVPN 2.0, you have to put the certification file of\n" +
            "# the destination VPN Server on the OpenVPN Client computer when you use this\n" +
            "# config file. Please refer the below descriptions carefully.\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# Specify the type of the layer of the VPN connection.\n" +
            "# \n" +
            "# To connect to the VPN Server as a \"Remote-Access VPN Client PC\",\n" +
            "#  specify 'dev tun'. (Layer-3 IP Routing Mode)\n" +
            "#\n" +
            "# To connect to the VPN Server as a bridging equipment of \"Site-to-Site VPN\",\n" +
            "#  specify 'dev tap'. (Layer-2 Ethernet Bridgine Mode)\n" +
            "\n" +
            "dev tun\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# Specify the underlying protocol beyond the Internet.\n" +
            "# Note that this setting must be correspond with the listening setting on\n" +
            "# the VPN Server.\n" +
            "# \n" +
            "# Specify either 'proto tcp' or 'proto udp'.\n" +
            "\n" +
            "proto tcp\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# The destination hostname / IP address, and port number of\n" +
            "# the target VPN Server.\n" +
            "# \n" +
            "# You have to specify as 'remote <HOSTNAME> <PORT>'. You can also\n" +
            "# specify the IP address instead of the hostname.\n" +
            "# \n" +
            "# Note that the auto-generated below hostname are a \"auto-detected\n" +
            "# IP address\" of the VPN Server. You have to confirm the correctness\n" +
            "# beforehand.\n" +
            "# \n" +
            "# When you want to connect to the VPN Server by using TCP protocol,\n" +
            "# the port number of the destination TCP port should be same as one of\n" +
            "# the available TCP listeners on the VPN Server.\n" +
            "# \n" +
            "# When you use UDP protocol, the port number must same as the configuration\n" +
            "# setting of \"OpenVPN Server Compatible Function\" on the VPN Server.\n" +
            "\n" +
            "remote 45.76.54.186 1314\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# The HTTP/HTTPS proxy setting.\n" +
            "# \n" +
            "# Only if you have to use the Internet via a proxy, uncomment the below\n" +
            "# two lines and specify the proxy address and the port number.\n" +
            "# In the case of using proxy-authentication, refer the OpenVPN manual.\n" +
            "\n" +
            ";http-proxy-retry\n" +
            ";http-proxy [proxy server] [proxy port]\n" +
            "\n" +
            "###############################################################################\n" +
            "# The encryption and authentication algorithm.\n" +
            "# \n" +
            "# Default setting is good. Modify it as you prefer.\n" +
            "# When you specify an unsupported algorithm, the error will occur.\n" +
            "# \n" +
            "# The supported algorithms are as follows:\n" +
            "#  cipher: [NULL-CIPHER] NULL AES-128-CBC AES-192-CBC AES-256-CBC BF-CBC\n" +
            "#          CAST-CBC CAST5-CBC DES-CBC DES-EDE-CBC DES-EDE3-CBC DESX-CBC\n" +
            "#          RC2-40-CBC RC2-64-CBC RC2-CBC\n" +
            "#  auth:   SHA SHA1 MD5 MD4 RMD160\n" +
            "\n" +
            "cipher AES-128-CBC\n" +
            "auth SHA1\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# Other parameters necessary to connect to the VPN Server.\n" +
            "# \n" +
            "# It is not recommended to modify it unless you have a particular need.\n" +
            "\n" +
            "resolv-retry infinite\n" +
            "nobind\n" +
            "persist-key\n" +
            "persist-tun\n" +
            "client\n" +
            "verb 3\n" +
            ";auth-user-pass\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# The certificate file of the destination VPN Server.\n" +
            "# \n" +
            "# The CA certificate file is embedded in the inline format.\n" +
            "# You can replace this CA contents if necessary.\n" +
            "# Please note that if the server certificate is not a self-signed, you have to\n" +
            "# specify the signer's root certificate (CA) here.\n" +
            "\n" +
            "<ca>\n" +
            "-----BEGIN CERTIFICATE-----\n" +
            "MIIDGzCCAgOgAwIBAgIJANLDaDLJVQ1FMA0GCSqGSIb3DQEBCwUAMA4xDDAKBgNV\n" +
            "BAMMA3ZwbjAeFw0xOTA1MjQwNzE1MzhaFw0yOTA1MjEwNzE1MzhaMA4xDDAKBgNV\n" +
            "BAMMA3ZwbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPKEKFxDxVUE\n" +
            "iCrGAky0ZwXu62rx9/raji3hZKva+lo6kF0BlS9tz8V52pBxP1jXsfML0JFhYlie\n" +
            "dEh4m90jHOpBajw2wpn8CoZdoZkAhSvDf59mNTAqlkStCEk5zaLquVX8Xss2hVMf\n" +
            "sRNmil0tqgq8c7dQ5gcmIlB6QSnJlDgLFtKlXWojNCcvY4xonp0mlmcascrkgq5G\n" +
            "aeeP8zmVaLYTGXjDAilM85Qr2X16xeiriTvsgjO8FHEFQwIB1+z8tEi5edGrr1ll\n" +
            "W4WkKPhl2JXs4Q4BUjWWpnuCvHtVBOOLqGjC23L7BonX6SGxDPu78lZdWr0aJfmW\n" +
            "rAvWTqOWCIsCAwEAAaN8MHowHQYDVR0OBBYEFDSuZyepi+yICPjN1wOzsC7b2rhA\n" +
            "MD4GA1UdIwQ3MDWAFDSuZyepi+yICPjN1wOzsC7b2rhAoRKkEDAOMQwwCgYDVQQD\n" +
            "DAN2cG6CCQDSw2gyyVUNRTAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkq\n" +
            "hkiG9w0BAQsFAAOCAQEAW8NED/vW0Or3TCl6zwict8nxhRI82xTX0Ev+ySYsCyI2\n" +
            "irUfD5JOHcmfwgm+/uonrRXyBSgpFdCtV/VBAfhheniNlYdGYwAIVAd631KtOOh5\n" +
            "Yerg+jpzljfTZqwBeE4X+V7o67mW+8NnSVrB6aCQXle2CHdUPpBr+WrmJRYGuC6B\n" +
            "UEMfSBwhFcmtyUhEBntbi86ZgubgGQiIdPthp5YypH6e5xjfL+HOCGUb8hJlQzkR\n" +
            "9dCnhSjQ9NE3NcsI2pO/8H/jsNaxm2b30UogWG0Jkc9nUh2Ae20Wo3gkrpGpj5sx\n" +
            "dSzaym7ofKcUdh1jzW5PWe1QF4Ykg6iOUl6OT7gvwA==\n" +
            "-----END CERTIFICATE-----\n" +
            "\n" +
            "</ca>\n" +
            "\n" +
            "\n" +
            "###############################################################################\n" +
            "# The client certificate file (dummy).\n" +
            "# \n" +
            "# In some implementations of OpenVPN Client software\n" +
            "# (for example: OpenVPN Client for iOS),\n" +
            "# a pair of client certificate and private key must be included on the\n" +
            "# configuration file due to the limitation of the client.\n" +
            "# So this sample configuration file has a dummy pair of client certificate\n" +
            "# and private key as follows.\n" +
            "\n" +
            "<cert>\n" +
            "-----BEGIN CERTIFICATE-----\n" +
            "MIIDOTCCAiGgAwIBAgIQbSI0IsxosAFVHhJzpUp35TANBgkqhkiG9w0BAQsFADAO\n" +
            "MQwwCgYDVQQDDAN2cG4wHhcNMTkwNTI0MDcxODMzWhcNMjIwNTA4MDcxODMzWjAR\n" +
            "MQ8wDQYDVQQDDAZjbGllbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\n" +
            "AQDfyPUwnhMicYatvBCRP9HgNQMKlnpED4AoJ7SBA/hc/CiyvpyuDYbYDQpqkdj8\n" +
            "wGQe9vxhDYMdgYAXx5l54mXAWaS91PGlqH7n3j3YDfvSjXUTEnQMIGNY600TTdkS\n" +
            "cDD4ucdYfSqHGgMosTxAONIvOSkEOrZOdcqsDH8JCvJ+K8kk7qbLFNQCcVQsz/eP\n" +
            "rr9EV3NBdlZhWRI8m7H1C3KDRHPHcFQbxhfKOxDWi2h8oJSY59HyBiVRwY4KVQVj\n" +
            "zIA9x9wUY/ntCQEOMflzQLPh9ijRkqRF2TnVEP26RzMtcEbpLMa00Y9mfpf0ty/d\n" +
            "2K8vZL5g5D7JcM1YGD6XaMT7AgMBAAGjgY8wgYwwCQYDVR0TBAIwADAdBgNVHQ4E\n" +
            "FgQUocsFdtiU6CefKmme6Sz/5cboBuswPgYDVR0jBDcwNYAUNK5nJ6mL7IgI+M3X\n" +
            "A7OwLtvauEChEqQQMA4xDDAKBgNVBAMMA3ZwboIJANLDaDLJVQ1FMBMGA1UdJQQM\n" +
            "MAoGCCsGAQUFBwMCMAsGA1UdDwQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAie3p\n" +
            "KV4NhmPR3aF6+ky0m0gbMDO99oVy7Noe30xpK8KGkDZMrvQv8WjM9Ko/etxx5gvz\n" +
            "cyzH2Q6a3+vmVJOirPzFua88FXACI25pLLMqYu1kb9IJYsjGw4x0l99CJ2wF/fzu\n" +
            "cCwhGlNKyiMscQiG6jv0FlpJgBQhRD/SpjmRSImniOXLhxNJi9bEn96t2DWXv0UM\n" +
            "nV/OlB7671dSgDBv8p5qM8/VF53ITvSPj152nQ+HSw1Tc5Ex9BY4GAGF4Q/rjdji\n" +
            "ERgu3sT/pM+DZX7g+SraBi+kaIfWzjR3dtcG0lGaA76JAdSgLzJwhod8twYh7m5F\n" +
            "rqUSijO9+WjP3C72cQ==\n" +
            "-----END CERTIFICATE-----\n" +
            "\n" +
            "</cert>\n" +
            "\n" +
            "<key>\n" +
            "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEowIBAAKCAQEA38j1MJ4TInGGrbwQkT/R4DUDCpZ6RA+AKCe0gQP4XPwosr6c\n" +
            "rg2G2A0KapHY/MBkHvb8YQ2DHYGAF8eZeeJlwFmkvdTxpah+59492A370o11ExJ0\n" +
            "DCBjWOtNE03ZEnAw+LnHWH0qhxoDKLE8QDjSLzkpBDq2TnXKrAx/CQryfivJJO6m\n" +
            "yxTUAnFULM/3j66/RFdzQXZWYVkSPJux9Qtyg0Rzx3BUG8YXyjsQ1otofKCUmOfR\n" +
            "8gYlUcGOClUFY8yAPcfcFGP57QkBDjH5c0Cz4fYo0ZKkRdk51RD9ukczLXBG6SzG\n" +
            "tNGPZn6X9Lcv3divL2S+YOQ+yXDNWBg+l2jE+wIDAQABAoIBAEKfeleiCAJOGBFr\n" +
            "FueXP21neuNRD09p6faKc5OhUfSk4ZztYIn03vs9TqeRii8dO/F4CIUAV9OV9UOf\n" +
            "GdMOkspkJcaaOeLeugFfybuj1h/GG1+1M7VUgx861jR0DbcOjZXPAUkX4mxcUypv\n" +
            "MYfRIsoKU2q96/6J1O/JvJw9lRn4cnnLAXBs17dClZ8tPRl16ZBfB7W/xtKfP9kG\n" +
            "KDVBONwThlVZ1bX0pcRHFsrhtRlw+FXNuWCUaiQyEeyU25nLGR1Dy20C0uMTFrkm\n" +
            "r2d2UqY9TL00GdmoqSQqndidy2/YrrI4ugAzz/Ex2Z2rTc0gX4YlpDXOm7gLsJt9\n" +
            "tPNpqPkCgYEA+u4hilZg+PpinKTsf5/qAzxwWreupqqNl5gXydy+NvxIDS4QA59Y\n" +
            "tGzBEPfa1UWcrX31sQyrfnv/l59N2mb0tVqJf5eNGjKgVfyCBOa6uRHN969qPMXi\n" +
            "E2d5K+skR65kZjHIJ8TpFYb7ONSNhfkqFq0gP3JsqnKsbugjmiO4Lo0CgYEA5E5s\n" +
            "62Q7dQ4kP+y5SBAPAtO2pxybyi/EiDFd9U1bSI1ln861yFIzKWKiirbwtbUhqeZR\n" +
            "RzfBZ4TkMXQBZ86iquhSkkW6jCZktVpHhP5xFwdRSVxnNn8vQd2v73jijG154CCQ\n" +
            "WX1aUsk/+PXSrf6Uh39aQjB+TbN5Kj2KmCFBw6cCgYB1yFUCBC2ccJrdACTqevty\n" +
            "7Wmni1R1ctTndUKlQ/IdCSog1aA6sw8GEY5GErErLnOuk9NBebr9seJ1HxeCDpWK\n" +
            "kqa7tz1KML1F3zKAbnTy7cKKIlJxmEjX5tffn431/4us1G0pDaqCqks9j7emTSBO\n" +
            "aJEcdu8+ynjZzij37xBC+QKBgHOx1npW+dZwyyfl02LUWHcLSKVY1w3XtRV7Ruz3\n" +
            "PYn/tX8NZotUNH8Fb+8xk7vRRXTutUOM2qKV8nmpGsk7Kq3HO4jKcyVwk1pfnJyl\n" +
            "wDN2TtgJTniMbStIp06IiO220KsmdWAUKQCI4bVNBW2M9EHR5LBkGK1RhNZGB4Te\n" +
            "XZBDAoGBAKyMdtrL1t/qy5/4fYw2+h5DzgkYISgVOdoJYJlFaZS0dRqym5Rhnzhm\n" +
            "i8qEI4nTSEPejeb2AthipFX0+WG1EY+A7O6Vacgc6uR20VXLCguQaEYyZFCK1d1B\n" +
            "k6lpittssoMqRtmaE1MvB8Oe2x7Nnd3ll0egEt5AyVq6nAtq+6Ev\n" +
            "-----END RSA PRIVATE KEY-----\n" +
            "\n" +
            "</key>\n";

    private String TAG = "TAG";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        addVPNStatusListener(this);
        findViewById(R.id.btn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                loadVpnProfile(data);
                getVpnProfile().mName = "vpn";
                connectVpn();
            }
        });

        findViewById(R.id.btn_stop).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                stopVpn();
            }
        });

        findViewById(R.id.btn_log).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d(TAG, "isRunning: " + isRunning());
            }
        });
    }

    @Override
    public void onConnectStart() {
        Log.d(TAG, "开始连接");
    }

    @Override
    public void onConnected() {
        Log.d(TAG, "已连接");
    }

    @Override
    public void onPaused() {
        Log.d(TAG, "已暂停");
    }

    @Override
    public void onNoNetwork() {
        Log.d(TAG, "无网络");
    }

    @Override
    public void onConnectClose() {
        Log.d(TAG, "连接关闭");
    }

    @Override
    public void onAuthFailed() {
        Log.d(TAG, "认证失败");
    }

    @Override
    public void onUnknown() {
        Log.d(TAG, "未知错误");
    }
}
